#
# TABLE STRUCTURE FOR: RSI_SEAT
#

DROP TABLE IF EXISTS RSI_SEAT;

CREATE TABLE RSI_SEAT (
  ID int(11) NOT NULL,
  SEAT_ROW int(11) NOT NULL,
  SEAT_NUMBER int(11) NOT NULL,
  AUDITORIUM_ID int(11) NOT NULL,
  PRIMARY KEY (ID),
  KEY AUDITORIUM_ID (AUDITORIUM_ID),
  CONSTRAINT RSI_SEAT_ibfk_1 FOREIGN KEY (AUDITORIUM_ID) REFERENCES RSI_AUDITORIUM (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (1, 1, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (1, 2, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (1, 3, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (1, 4, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (1, 5, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (2, 1, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (2, 2, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (2, 3, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (2, 4, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (2, 5, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (3, 1, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (3, 2, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (3, 3, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (3, 4, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (3, 5, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (4, 1, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (4, 2, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (4, 3, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (4, 4, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (4, 5, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (5, 1, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (5, 2, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (5, 3, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (5, 4, 1);
INSERT INTO RSI_SEAT (SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (5, 5, 1);
