#
# TABLE STRUCTURE FOR: RSI_AUDITORIUM
#

DROP TABLE IF EXISTS `RSI_AUDITORIUM`;

CREATE TABLE `RSI_AUDITORIUM` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `SEATS_NUMBER` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO RSI_AUDITORIUM (NAME, SEATS_NUMBER) VALUES ('nulla', 25);
INSERT INTO RSI_AUDITORIUM (NAME, SEATS_NUMBER) VALUES ('eligendi', 25);
INSERT INTO RSI_AUDITORIUM (NAME, SEATS_NUMBER) VALUES ('cum', 25);
INSERT INTO RSI_AUDITORIUM (NAME, SEATS_NUMBER) VALUES ('iste', 25);
INSERT INTO RSI_AUDITORIUM (NAME, SEATS_NUMBER) VALUES ('optio', 25);


