#
# TABLE STRUCTURE FOR: RSI_CLIENT
#

DROP TABLE IF EXISTS RSI_CLIENT;

CREATE TABLE RSI_CLIENT (
  ID int(11) NOT NULL,
  USERNAME varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  PASSWORD varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO RSI_CLIENT (ID, USERNAME, PASSWORD) VALUES (1, 'davis.florida', 'qui');
INSERT INTO RSI_CLIENT (ID, USERNAME, PASSWORD) VALUES (2, 'daisy71', 'laboriosam');
INSERT INTO RSI_CLIENT (ID, USERNAME, PASSWORD) VALUES (3, 'eferry', 'iste');
INSERT INTO RSI_CLIENT (ID, USERNAME, PASSWORD) VALUES (4, 'bhudson', 'iure');
INSERT INTO RSI_CLIENT (ID, USERNAME, PASSWORD) VALUES (5, 'geoffrey74', 'voluptate');


