#
# TABLE STRUCTURE FOR: RSI_SEAT
#

DROP TABLE IF EXISTS RSI_SEAT;

CREATE TABLE RSI_SEAT (
  ID int(11) NOT NULL,
  SEAT_ROW int(11) NOT NULL,
  SEAT_NUMBER int(11) NOT NULL,
  AUDITORIUM_ID int(11) NOT NULL,
  PRIMARY KEY (ID),
  KEY AUDITORIUM_ID (AUDITORIUM_ID),
  CONSTRAINT RSI_SEAT_ibfk_1 FOREIGN KEY (AUDITORIUM_ID) REFERENCES RSI_AUDITORIUM (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (1, 3, 3, 3);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (2, 1, 4, 1);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (3, 2, 4, 5);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (4, 4, 5, 2);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (5, 4, 4, 3);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (6, 3, 3, 1);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (7, 2, 4, 3);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (8, 2, 4, 1);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (9, 4, 3, 5);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (10, 5, 2, 3);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (11, 1, 1, 3);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (12, 3, 5, 5);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (13, 2, 5, 4);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (14, 5, 2, 1);
INSERT INTO RSI_SEAT (ID, SEAT_ROW, SEAT_NUMBER, AUDITORIUM_ID) VALUES (15, 4, 2, 3);


