#
# TABLE STRUCTURE FOR: RSI_AUDITORIUM
#

DROP TABLE IF EXISTS `RSI_AUDITORIUM`;

CREATE TABLE `RSI_AUDITORIUM` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `SEATS_NUMBER` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO RSI_AUDITORIUM (ID, NAME, SEATS_NUMBER) VALUES (1, 'nulla', 5);
INSERT INTO RSI_AUDITORIUM (ID, NAME, SEATS_NUMBER) VALUES (2, 'eligendi', 5);
INSERT INTO RSI_AUDITORIUM (ID, NAME, SEATS_NUMBER) VALUES (3, 'cum', 5);
INSERT INTO RSI_AUDITORIUM (ID, NAME, SEATS_NUMBER) VALUES (4, 'iste', 5);
INSERT INTO RSI_AUDITORIUM (ID, NAME, SEATS_NUMBER) VALUES (5, 'optio', 5);


