#
# TABLE STRUCTURE FOR: RSI_SEAT_RESERVED
#

DROP TABLE IF EXISTS RSI_SEAT_RESERVED;

CREATE TABLE RSI_SEAT_RESERVED (
  ID int(11) NOT NULL,
  SEAT_ID int(11) NOT NULL,
  RESERVATION_ID int(11) NOT NULL,
  SCREENING_ID int(11) NOT NULL,
  PRIMARY KEY (ID),
  KEY SEAT_ID (SEAT_ID),
  KEY RESERVATION_ID (RESERVATION_ID),
  KEY SCREENING_ID (SCREENING_ID),
  CONSTRAINT RSI_SEAT_RESERVED_ibfk_1 FOREIGN KEY (SEAT_ID) REFERENCES RSI_SEAT (ID),
  CONSTRAINT RSI_SEAT_RESERVED_ibfk_2 FOREIGN KEY (RESERVATION_ID) REFERENCES RSI_RESERVATION (ID),
  CONSTRAINT RSI_SEAT_RESERVED_ibfk_3 FOREIGN KEY (SCREENING_ID) REFERENCES RSI_SCREENING (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO RSI_SEAT_RESERVED (SEAT_ID, RESERVATION_ID, SCREENING_ID) VALUES (13, 3, 7);
INSERT INTO RSI_SEAT_RESERVED (SEAT_ID, RESERVATION_ID, SCREENING_ID) VALUES (13, 3, 5);
INSERT INTO RSI_SEAT_RESERVED (SEAT_ID, RESERVATION_ID, SCREENING_ID) VALUES (2, 5, 10);
INSERT INTO RSI_SEAT_RESERVED (SEAT_ID, RESERVATION_ID, SCREENING_ID) VALUES (12, 9, 3);
INSERT INTO RSI_SEAT_RESERVED (SEAT_ID, RESERVATION_ID, SCREENING_ID) VALUES (2, 4, 10);
INSERT INTO RSI_SEAT_RESERVED (SEAT_ID, RESERVATION_ID, SCREENING_ID) VALUES (8, 1, 9);
INSERT INTO RSI_SEAT_RESERVED (SEAT_ID, RESERVATION_ID, SCREENING_ID) VALUES (2, 5, 8);
INSERT INTO RSI_SEAT_RESERVED (SEAT_ID, RESERVATION_ID, SCREENING_ID) VALUES (13, 9, 1);
INSERT INTO RSI_SEAT_RESERVED (SEAT_ID, RESERVATION_ID, SCREENING_ID) VALUES (8, 8, 2);
INSERT INTO RSI_SEAT_RESERVED (SEAT_ID, RESERVATION_ID, SCREENING_ID) VALUES (4, 10, 9);


